apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falseflag-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: falseflag
    falseflag.dev/environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/Zagrit-HQ/false-flag-demo.git
      targetRevision: "1.*.*"
      path: deploy/helm/falseflag-operator
      helm:
        releaseName: falseflag
        valueFiles:
          - $values/production/values.yaml
    - repoURL: https://github.com/Zagrit-HQ/false-flag-gitops.git
      targetRevision: refs/heads/main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falseflag-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
