apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falseflag-preview-pr-1
  namespace: argocd
  annotations:
    falseflag.dev/created-at: "2026-05-29T15:34:07Z"
  labels:
    app.kubernetes.io/name: falseflag
    falseflag.dev/environment: preview
    falseflag.dev/preview: pr-1
    falseflag.dev/pr: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/Zagrit-HQ/false-flag-demo.git
      targetRevision: refs/heads/wito/some-change
      path: deploy/helm/falseflag-operator
      helm:
        releaseName: falseflag
        valueFiles:
          - $values/preview/pr-1/values.yaml
        parameters:
          - name: image.tag
            value: $ARGOCD_APP_REVISION_SHORT_8
            forceString: true
    - repoURL: https://github.com/Zagrit-HQ/false-flag-gitops.git
      targetRevision: refs/heads/main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falseflag-preview-pr-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 20
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
